### ISSUE TITLE
需要mySQL数据库备份

### ISSUE THREAD

**Issue by asapabedi** [summerblue/phphub5#111]
我可以从你的数据库获取一个mySQL备份，在没有SSH的情况下使用共享主机，我需要将数据库备份上传到我的服务器

**Comment by overtrue** [comment]
Please describe it in English.

发自我的 iPhone

**Comment by asapabedi** [comment]
Can i get a mySQL backup from your database, I use shared hosting without ssh, I need to upload the database.sql backup file to my server using phpmyadmin, everything seems to be working fine except for the database connection.

**Comment by asapabedi** [comment]
Requires mySQL database backup for installation on shared hosting

**Comment by overtrue** [comment]
you can export the SQL file from your local dev environment.
