### ISSUE TITLE
写的这么烂，还商业授权...

### ISSUE THREAD

**Issue by tangzhangming** [summerblue/phphub5#113]
thujohn/rss 这个开发版包都不能用了
访问admin直接跳转到http://phphub5.app/auth/callback?driver=github&.....

**Comment by summerblue** [comment]
![image](https://user-images.githubusercontent.com/324764/33045899-9533a492-ce89-11e7-859a-54a428fa064a.png)

![image](https://user-images.githubusercontent.com/324764/33045937-c330ada4-ce89-11e7-9afe-a080f12549cf.png)

> 可惜工作的几年，已经把写作习惯丢了，虽然阅读习惯还在，每个月还是保持至少四五十个小时的阅读时间，但是确确实实，没怎么写过东西，人本来就宅，半年难得和生人说几句话，再加上不写作，感觉语言能力都退化了，和人说话都有点结巴，趁最近接触wordpress，就想着干脆搭建个博客，适当写作下，免得真的把交流能力完全退化掉。

如此出言不逊！不过看到你的 [博客](http://tangzhangming.com/archives/26.html) ，气就消了，很好奇你在哪找到工作的。
