### ISSUE TITLE
 关于smartisan/follow

### ISSUE THREAD

**Issue by stevejobsii** [summerblue/phphub5#12]
关于smartisan/follow
![qq 20160825094358](https://cloud.githubusercontent.com/assets/12492618/17953737/8280490e-6aa8-11e6-81ba-95274c9e3724.png)

这个laravel framework  只是5.1，  但是这里需要最新的laravel/laravel,如何跳个这个require dev？？？谢谢！！！
这个phphub插件需要最新版的laravel，但是phphub使用的 laravel框架只是5.1，那么composer require smartisan/follow老是出错，该如何破？谢谢！

**Comment by stevejobsii** [comment]
难道要手动下载这个包，手动改了这个packagist放到app里面了？

**Comment by korneliuskristianr** [comment]
I'm having error with this ( **smartisan/follow**) package. It seems that package doesn't exist anymore. Any help please!

**Comment by stevejobsii** [comment]
@korneliuskristianr I fix this problem. This package is still exist but you should change the name of composer.json name,for example "name": "laravel/myapp" ,not "laravel/laravel".

**Comment by Jesseyx** [comment]
@stevejobsii thanks. But when do that, this package will install laravel/laravel, the composer prompt class conflicted...

**Comment by Osub** [comment]
我也有这个问题

**Comment by blueskylsl** [comment]
smartisan/follow的git仓库应该是被原作者删除了，可以在composer.json的repositories数组里加上{"type": "git", "url": "https://github.com/blueskylsl/follow"}，然后composer update一下就OK了 @Osub

**Comment by stevejobsii** [comment]
@blueskylsl good idea  应该是修改composer.lock
