### ISSUE TITLE
大大，开发环境是什么？

### ISSUE THREAD

**Issue by sucof** [summerblue/phphub5#15]
我用了ubuntu16.04+php7+homestead0.3+virtualbox-0.5.0.box，一直有各种错误，请问大大具体的开发环境是什么？
谢谢各位大大的指点。

**Comment by sucof** [comment]
vagrant为1.85，php试了5.6，仍然有错误

**Comment by sucof** [comment]
已解决，建议大大说明软件运行环境，比如说windows10，还是mac，还是ubuntu等。

**Comment by summerblue** [comment]
用的是 homestead ，ubuntu 14.04 的版本
