### ISSUE TITLE
bug： Installing smartisan/follow 错误

### ISSUE THREAD

**Issue by sucof** [summerblue/phphub5#16]
由于 https://github.com/mohd-isa/follow已经移除，所以composer install 会出现错误，需要进行修改

**Comment by stevejobsii** [comment]
修改composer.lock 中follow下载地址，改为stevejobsii/follow1,@sucof

**Comment by summerblue** [comment]
已修复，谢谢 @stevejobsii 的回复 https://github.com/summerblue/phphub5/commit/8243820f11c4b3957a293765cb214e07dfdbebc0
