### ISSUE TITLE
分享文章内部的跳转链接无法正常跳转

### ISSUE THREAD

**Issue by JobsLong** [summerblue/phphub5#21]
Bug 地址：https://laravel-china.org/topics/1349

![image](https://cloud.githubusercontent.com/assets/4585899/19017981/88c6fd28-8883-11e6-8bf0-34fa37f14d63.png)

点击该链接之后，跳转 404 错误：

```
https://laravel-china.org/topics/%5C%5Cwww.hagongyi.com
```

**Comment by summerblue** [comment]
markdown 解析器的问题
