### ISSUE TITLE
部署时错误：smartisan/follow

### ISSUE THREAD

**Issue by PCDotFan** [summerblue/phphub5#22]
前几天是正常的……回去看了下 [Packagist](https://packagist.org/packages/smartisan/follow) 貌似项目已经被删除了，有可能是这个原因吗？

```
$ composer install

Problem 1
    - smartisan/follow dev-master requires laravel/laravel >= 5.1 -> no matching package found.
    - smartisan/follow dev-master requires laravel/laravel >= 5.1 -> no matching package found.
    - Installation request for smartisan/follow dev-master -> satisfiable by smartisan/follow[dev-master].
```

**Comment by lookas2001** [comment]
其实这个项目里包含了这个包 在/packages/follow
不过我不太清楚如何使用这个东东。。
不知道为什么 已经在composer.json里配置了
    "repositories": [
        {
            "type": "path",
            "url": "packages/rss"
        },
        {
            "type": "path",
            "url": "packages/follow"
        }
composer仍然无法识别

**Comment by daimingkang** [comment]
把项目名字改一下name:  laravel/laravel  我改成了自己的项目名字
