### ISSUE TITLE
初始化数据结构时出错 unique key is too long, even if specified

### ISSUE THREAD

**Issue by kisexu** [summerblue/phphub5#26]
使用的是 MariaDB 数据库 utf8mb

![snip20161009_3](https://cloud.githubusercontent.com/assets/1040190/19219054/a02398ec-8e3b-11e6-95ed-a67e83a631cf.png)

**Comment by overtrue** [comment]
@kisexu 你应该是执行了两次 Migrate, 上一次一些表已经建立成功了，所以你需要清理后重新 migrate
