### ISSUE TITLE
安装命令 执行没反应

### ISSUE THREAD

**Issue by rain-hon** [summerblue/phphub5#36]
用的本地搭建的环境，不是用的homestead

windows系统，前面已经复制了.env 编辑了配置，执行了composer install，在下面这一步卡住了,
运行 php artisan est:install
执行到 php artisan migrate --seed 时卡住没反应了

单独执行该命令，报下面的错误
```
  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `
  revisions` add index `revisions_revisionable_id_revisionable_type_index`(`revisionable_id`, `revisionable_type`))

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
```

**Comment by overtrue** [comment]
@rain-hon 请检查数据库引擎  FYI #39

**Comment by Twitchboy** [comment]
* 本地环境 homestead搭建的，nginx+php7.0+mysql5.7+ubuntu16.04lts
在执行安装命令时
````
vagrant@homestead:~/Code/phphub5$ php artisan est:install
---
php artisan key:generate
Application key [9atI6oXHRuuOntR5hEc3vBGLZpSvRi88] set successfully.

---
---
php artisan migrate --seed

```` 
就卡在这了！！！也不报错！

**Comment by KingSamuel** [comment]
vagrant@homestead:~/Code/phphub5$ php artisan est:install
---
php artisan key:generate
Application key [l5vfEk7mrD78FbaLsdN75JkY5jCWRG9l] set successfully.

---
---
php artisan migrate --seed
yes
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 >
Migration table created successfully.
Migrated: 2013_04_09_062329_create_revisions_table
Migrated: 2014_04_24_110151_create_oauth_scopes_table
Migrated: 2014_04_24_110304_create_oauth_grants_table
Migrated: 2014_04_24_110403_create_oauth_grant_scopes_table
Migrated: 2014_04_24_110459_create_oauth_clients_table
Migrated: 2014_04_24_110557_create_oauth_client_endpoints_table
Migrated: 2014_04_24_110705_create_oauth_client_scopes_table
Migrated: 2014_04_24_110817_create_oauth_client_grants_table
Migrated: 2014_04_24_111002_create_oauth_sessions_table
Migrated: 2014_04_24_111109_create_oauth_session_scopes_table
Migrated: 2014_04_24_111254_create_oauth_auth_codes_table
Migrated: 2014_04_24_111403_create_oauth_auth_code_scopes_table
Migrated: 2014_04_24_111518_create_oauth_access_tokens_table
Migrated: 2014_04_24_111657_create_oauth_access_token_scopes_table
Migrated: 2014_04_24_111810_create_oauth_refresh_tokens_table
Migrated: 2016_05_09_154236_create_tags_table
Migrated: 2016_07_03_015719_create_topics_table
Migrated: 2016_07_03_020659_create_sitestatuses_table
Migrated: 2016_07_03_020714_create_replies_table
Migrated: 2016_07_03_020734_create_links_table
Migrated: 2016_07_03_020815_create_appends_table
Migrated: 2016_07_03_020818_create_attentions_table
Migrated: 2016_07_03_021130_create_votes_table
Migrated: 2016_07_03_021841_create_users_table
Migrated: 2016_07_03_023927_create_categories_table
Migrated: 2016_07_03_222952_entrust_setup_tables
Migrated: 2016_07_06_014514_create_notifications_table
Migrated: 2016_07_08_154127_create_banners_table
Migrated: 2016_07_17_094053_create_followers_table
Migrated: 2016_07_17_145102_create_active_users_table
Migrated: 2016_07_17_215720_create_hot_topics
Migrated: 2016_07_23_162047_create_sites_table
Migrated: 2016_07_28_102537_create_notificationmaillogs_table
Migrated: 2016_07_28_104715_create_failed_jobs_table
Migrated: 2016_10_16_225901_create_maintainer_logs
Migrated: 2016_12_15_071034_add_signature_to_users_table
Migrated: 2017_01_08_153204_create_blogs_table
Migrated: 2017_01_15_154051_add_articles_count_to_users_table
Migrated: 2017_01_17_102202_add_password_filed_to_users_table
Migrated: 2017_02_10_064041_setup_draft
别傻了? 这是线上环境呀。
---
---
php artisan est:init-rbac
Users table is empty

---
