### ISSUE TITLE
Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by HiYangZhi** [summerblue/phphub5#39]
安装的时候提示： 

[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (S
  QL: alter table `revisions` add index `revisions_revisionable_id_revisionable_type_index`(`revisionable_id`, `revis
  ionable_type`))

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

看说明是索引组合后最大长度超限制了，不知道大家是怎么解决的。我用的MYSQL

**Comment by HiYangZhi** [comment]
是我表类型弄错了，默认的是MYISAM，要改成INNODB

**Comment by ljmready** [comment]
记录一下。。
用myisam引擎也是不行的。
出现这个问题的原因是phphub的表的排序规则是utf8mb4，相比utf8多了一个byte。
因此对varchar(255)做索引时，utf8mb4规则下会超过mysql的索引字节限制。
用utf8_unicode_ci时，767/3 = 255.7，255刚好
用utf8mb4_unicode_ci时，767/4 = 191.8，255就超过了。

解决方案：把需要加索引的varchar字段长度设置成191
如：
$table->string('name', 191);
$table->string('redirect_uri', 191);

具体改看哪个文件，我是全文搜索的来改的
