### ISSUE TITLE
windows按照安装文档操作 ，操作到npm install --no-bin-links报错，求高手指点

### ISSUE THREAD

**Issue by terrywamg** [summerblue/phphub5#4]
D:\websites\phphub5>npm install --no-bin-links
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\browserify requires glob@'^4.0.5' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-less\node_modules\accord requires glob@'7.0.3' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-logger requires chalk@'^0.5.1' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\chalk,
npm WARN unmet dependency which is version 1.1.3
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-logger requires gulp-util@'^3.0.0' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-util,
npm WARN unmet dependency which is version 2.2.20
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\jshint requires minimatch@'2.0.x' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\minimatch,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\jshint requires lodash@'3.7.x' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-jshint\node_modules\gulp-util requires through2@'^2.0.0' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-jshint\node_modules\through2,
npm WARN unmet dependency which is version 0.6.5
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-jshint\node_modules\rcloader requires lodash@'~2.4.1' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-util\node_modules\chalk requires supports-color@'^0.2.0' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\supports-color,
npm WARN unmet dependency which is version 3.1.2
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-todo\node_modules\gulp-util requires through2@'^2.0.0' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-todo\node_modules\through2,
npm WARN unmet dependency which is version 0.6.5
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpunit\node_modules\gulp-messenger\node_modules\gulp-debug\node_modules\gulp-util requires object-assign@'^3.0.0' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpunit\node_modules\gulp-messenger\node_modules\gulp-debug\node_modules\object-assign,
npm WARN unmet dependency which is version 4.1.0
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-phpunit\node_modules\gulp-util\node_modules\chalk requires supports-color@'^0.2.0' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\supports-color,
npm WARN unmet dependency which is version 3.1.2
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass requires glob@'^7.0.3' but will load
npm WARN unmet dependency D:\websites\phphub5\node_modules\laravel-elixir\node_modules\glob,
npm WARN unmet dependency which is version 5.0.15
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package laravel-elixir@4.2.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer laravel-elixir-livereload@1.1.6 wants laravel-elixir@^5.0

npm ERR! Please include the following file with any support request:
npm ERR!     D:\websites\phphub5\npm-debug.log

**Comment by summerblue** [comment]
请使用 homestead http://laravel-china.org/docs/5.1/homestead。

国内用户可以考虑使用此方法加速 NPM 下载：https://phphub.org/topics/2102
