### ISSUE TITLE
安装完毕后直接访问admin  直接跳转到github登录窗口??

### ISSUE THREAD

**Issue by DavidCao626** [summerblue/phphub5#40]
php artisan est:install  执行完毕后  登录管理后台：http://phphub5.app/admin  直接转github登录窗口吗？并不是像文档所说  "在开发环境下，直接访问后台地址即可登录 1 号用户。"

 另外.env 文件
// Github oauth
CLIENT_ID=eefd4111fbcb0e1d0fb9
CLIENT_SECRET=3dce7078f20bc10a1f6bef559b81787648f1b372

// Github Card
GITHUB_CARD_CLIENT_ID=eefd4111fbcb0e1d0fb9
GITHUB_CARD_CLIENT_SECRET=3dce7078f20bc10a1f6bef559b81787648f1b372

这些CLIENT_ID、CLIENT_SECRET貌似是生产环境的.......

**Comment by summerblue** [comment]
修改 .env 的 debug 等于 true
