### ISSUE TITLE
button按钮的一个BUG

### ISSUE THREAD

**Issue by W3INFO** [summerblue/phphub5#41]
注意到作者@summerblue在最近10天内更新了部分文件

在本地测试时发现后台管理用户按钮失效的BUG，如图（点击按钮无效）

![1](https://cloud.githubusercontent.com/assets/17700488/20510623/c341d29c-b0ac-11e6-8e16-402db32cf3d1.png)

**Comment by summerblue** [comment]
Chrome 浏览器下无法重现，前后台样式是分离的。
