### ISSUE TITLE
帖子内容格式导致页面样式错乱

### ISSUE THREAD

**Issue by JobsLong** [summerblue/phphub5#44]
出错地址：https://laravel-china.org/topics/1932

**Comment by overtrue** [comment]
应该是内容超过了 TEXT 的长度

**Comment by oceanpad** [comment]
@overtrue 为什么安装composer的overtrue/laravel-follow的时候安装错误呢？failded to download。

**Comment by overtrue** [comment]
@oceanpad 应该是你的网络原因

**Comment by overtrue** [comment]
@oceanpad 截图看看

**Comment by oceanpad** [comment]
@overtrue 这个样子的，之前安装其他的composer.json的东西都已经安装完毕。
![screen shot 2017-01-02 at 4 40 23 pm](https://cloud.githubusercontent.com/assets/13033318/21586304/5a926f58-d10a-11e6-8354-077871c64af0.png)

**Comment by summerblue** [comment]
@oceanpad https://github.com/summerblue/phphub5/issues/51#issuecomment-271714077
