### ISSUE TITLE
some package missing like summerblue/turbo ？？

### ISSUE THREAD

**Issue by xus898** [summerblue/phphub5#49]

**Comment by lenkaren** [comment]
一样的问题
The same problem.

**Comment by 321dh** [comment]
遇到同样的问题

**Comment by springjk** [comment]
修改 `composer.yml` 

`"summerblue/turbo": "^0.3.2",`
to
`"rcrowe/turbo": "^0.3.0",`

@summerblue 的这个项目删除了，看起来是一样的东西，或许 summer 做过一些修改，我不知道其中的原委，但是目前可以工作。

**Comment by xus898** [comment]
👌 ，暂且这样子；
