### ISSUE TITLE
项目安装成功，后台管理登陆访问不过去了

### ISSUE THREAD

**Issue by Twitchboy** [summerblue/phphub5#50]
前台phphub5.app正常；但是访问phphub5.app/admin 不行了！
````
跳转链接：http://phphub.app/login?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=Yh2tHZcB03ZEdLB7sou3LPVRkw7FyHVl0F49WI4i

````

**Comment by bys1123** [comment]
没错，我的也是会自动跳转到phphub.app

**Comment by bys1123** [comment]
呃，Summer是不是把报错信息写URL里了……

**Comment by summerblue** [comment]
> 请修改 `.env` 文件为 `APP_ENV=local` 和 `APP_DEBUG=true` 。

**Comment by Twitchboy** [comment]
修改后OK了！

**Comment by Twitchboy** [comment]
完美解决问题！！！

**Comment by wulikanhua** [comment]
修改了.env文件，但是还是跳转到http://phphub.app/login?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=6dcQ5LIEE121cbCRg5EEinvXqEaeCvH0bQsRzsH3请问是什么原因呢

**Comment by bys1123** [comment]
@wulikanhua 要改一下env的Github key配置
