### ISSUE TITLE
项目composer install的时候报错

### ISSUE THREAD

**Issue by a1292717155** [summerblue/phphub5#51]
`Failed to download overtrue/laravel-follow from dist: The "https://api.github.com/repos/overtrue/laravel-follow/zipball/2ad4d232ccccd1cf4a680794d358d243097b870f" file could not be downloaded (HTTP/1.1 302 Found)
    Now trying to download from source`

**Comment by maclinuxp** [comment]
我也遇到了，咋回事

**Comment by lenkaren** [comment]
下载有问题了，修改下composer.lock的代码，把2392行的head路径改为：
`"reference": "5d49bfce854ef093d02a44668fa184054cb52167"`

他是想去这里下载东西 https://github.com/overtrue/laravel-follow
