### ISSUE TITLE
建议修改mysql默认字符集，不然执行迁移会出错

### ISSUE THREAD

**Issue by rovast** [summerblue/phphub5#56]
文件路径`config/database.php`，修改mysql配置
``` php
'mysql' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'localhost'),
            'database'  => env('DB_DATABASE', 'forge'),
            'username'  => env('DB_USERNAME', 'forge'),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8', // changed
            'collation' => 'utf8_unicode_ci', // changed
            'prefix'    => '',
            'strict'    => false,
        ],
`

**Comment by overtrue** [comment]
这并不是解决问题的方式，utf8mb4 支持 emoji, 而 utf8 是不支持的。

**Comment by rovast** [comment]
哦~ 我也是刚接触，想通过看源码来熟悉`laravel`的，但是按照默认的配置，会报错说`key`值长度有限，最后排查到应该是字符集编码的问题。然后我参考laravel官方的`database.php`来修改的。
那使用utf8mb4如何进行正确的迁移呢

**Comment by overtrue** [comment]
> https://github.com/laravel/laravel/pull/4077
> https://github.com/laravel/laravel/pull/4050

三个方案：

1. 使用 MySQL 5.7 + 
2. 我在 stackoverflow 看到一个解决方案(没试过哈)：

```
SET @@global.innodb_large_prefix = 1;
```

3. 在你的项目里把 migrations 中的字段大于 255 长度的 string 改成 255

以上是按容易度优先级排序的 😄

**Comment by rovast** [comment]
感谢指导~ 升级Mysql后已解决

**Comment by overtrue** [comment]
@rovast 你果断选择了最简单方式哈哈

**Comment by BruceGujinhe** [comment]
按照前两种都没有解决成功。
