### ISSUE TITLE
Master 的 BLOG_CATEGORY_ID 配置缺失

### ISSUE THREAD

**Issue by springjk** [summerblue/phphub5#57]
Master 分支中的 `.env.example` 文件缺少 `BLOG_CATEGORY_ID=8`，`phphub.blog_category_id` 没有默认值，主分支中有查询使用了此配置，导致进入个人中心报错。

因为没有 releases，所以只能把 master 应看成 releases 了。

另外，为什么有
* `phphub.blog_category_id`
* `app.wiki_topic_id`

这样的配置，不放在一起有些困惑，是不是放在一起更好一些。

**Comment by summerblue** [comment]
好建议
