### ISSUE TITLE
Emoji 自动补全文bug

### ISSUE THREAD

**Issue by sucof** [summerblue/phphub5#61]
在文章编写处和发起讨论的正文编写处不能Emoji 自动补全，回复正常，https://laravel-china.org线上网站也是如此。

**Comment by summerblue** [comment]
文章编辑器使用： https://github.com/NextStepWebs/simplemde-markdown-editor 
自动补全使用了：https://github.com/yuku-t/jquery-textcomplete

simplemde 无法支持 emoji 补全，因为其底层使用了 CodeMirror ，simplemde 对 CodeMirror 的 Enter 做了绑定，而无法触发  textcomplete 的 enter 事件，至少我找不到比较好的方法。

更多的讨论见这里： https://github.com/yuku-t/jquery-textcomplete/issues/255
