### ISSUE TITLE
两处bug

### ISSUE THREAD

**Issue by sucof** [summerblue/phphub5#63]
1.在查看非本人专栏文章时，获得的文章是空因而显示出错get property of non-object的错误，而https://laravel-china.org网站是没有问题的，应该是大大忘记上传文件了，或者哪个版本不对？

2.传递参数出错，TopicsController::show()中有两个参数，一个id和request，但是在PagesController中还是用了以前的代码，只有一个参数，此错误在https://laravel-china.org的wiki显示中也是有问题的。

**Comment by eric1lubow** [comment]
我也碰到了
Trying to get property of non-object (View: /data/www/phphub5/resources/views/topics/partials/topics.blade.php) (View: /data/www/phphub5/resources/views/topics/partials/topics.blade.php)
