### ISSUE TITLE
添加类似简书似的专题是不是更容易找寻话题和学习？

### ISSUE THREAD

**Issue by sucof** [summerblue/phphub5#68]
添加类似简书似的专题是不是更容易找寻话题和学习？

**Comment by summerblue** [comment]
贴个链接给我瞧瞧你指的是什么

**Comment by sucof** [comment]
简单的说就是每个社区成员发帖或者写专栏文章的时候，不止能选择分类，也能选择一些标签（简书叫专题吧），例如：laravel教程，laravel实战，新技术，生活见闻等，然后根据浏览或文章创建记录，在登陆用户页面推荐一些标签集合，而不是单单推荐文章，例如http://www.jianshu.com/recommendations/collections?utm_medium=index-collections&utm_source=desktop所展示的，当然，laravel社区内容比较集中，以laravel为主，这功能和summerblue大大的分类功能也是有点重合。小小的建议，不过个人感觉要是有个这样的推荐标签（主题），对于查看社区文章还是能方便些。

**Comment by summerblue** [comment]
老牛逼了，我一直有在想，不过：
1. 实现起来还是需要花点时间；
2. 就如你说到的，社区文章现在其实还不到那么多。

后面这个功能肯定会加的 🌹

**Comment by sucof** [comment]
summerblue大大威武
