### ISSUE TITLE
更新后帖子详情报错

### ISSUE THREAD

**Issue by dancelion** [summerblue/phphub5#69]
![image](https://cloud.githubusercontent.com/assets/7478515/24097006/0a100c8a-0d9f-11e7-996a-357aa1f3f07a.png)

**Comment by dancelion** [comment]
users/1 报错
![image](https://cloud.githubusercontent.com/assets/7478515/24101907/01febbac-0db5-11e7-9baf-37252ec3daf3.png)

**Comment by summerblue** [comment]
请最新最新版本
