### ISSUE TITLE
最新版重新安装的还是报错

### ISSUE THREAD

**Issue by dancelion** [summerblue/phphub5#71]
用户主页和专栏详情报错 其他的正常
![image](https://cloud.githubusercontent.com/assets/7478515/24128601/eea00f9e-0e17-11e7-8858-707eed4a26b3.png)
![image](https://cloud.githubusercontent.com/assets/7478515/24128613/03f48ea6-0e18-11e7-93f3-8ee60248b671.png)

**Comment by haojingliu** [comment]
db里有这条数据吗

**Comment by dancelion** [comment]
topic表里有 但是blog_topics表里是空的

**Comment by sucof** [comment]
这个一般是种子文件没写数据，自己修改下就行
