### ISSUE TITLE
Exception with command ”artisan migarate“

### ISSUE THREAD

**Issue by BruceGujinhe** [summerblue/phphub5#81]
[Symfony\Component\Debug\Exception\FatalErrorException]
Trait 'Overtrue\LaravelFollow\FollowTrait' not found

**Comment by overtrue** [comment]
@BruceGujinhe sorry, 是我的坑，你的版本是不是用的 dev-master ？ 如果是的话有两个解决方案：

1. 按新版的语法改一下名称：https://github.com/overtrue/laravel-follow
2. 将版本锁定为  1.0.* 然后 update 即可。

这是我的锅。

**Comment by BruceGujinhe** [comment]
确实是dev-master，谢谢答复！
