### ISSUE TITLE
Suggestion add preview function when we edit posts

### ISSUE THREAD

**Issue by BruceGujinhe** [summerblue/phphub5#82]
I found that it doesn't support all the  md grammars in post dialog, but it's quite perfect in the comment dialog. (such as '#'  doesn't work in post dialog, It works well in comment dialog.) I always could find something wrong within layout after saving posts then i have to return the post dialog to edit my post again.
So I suggest to add markdown preview when we edit posts.

**Comment by summerblue** [comment]
![image](https://cloud.githubusercontent.com/assets/324764/25324669/9f7421ec-28f9-11e7-8b81-0c53dd7393f8.png)
