### ISSUE TITLE
Show posts is different from editing model

### ISSUE THREAD

**Issue by BruceGujinhe** [summerblue/phphub5#83]
Edit :
![image](https://github.com/BruceGujinhe/laravelblogForLC/blob/master/public/upload/cutimgs/edit%20with%20md.png?raw=true)
But show within posts:
![image](https://github.com/BruceGujinhe/laravelblogForLC/blob/master/public/upload/cutimgs/show%20posts.png?raw=true)

**Comment by summerblue** [comment]
h1 is not allowed
