### ISSUE TITLE
overtrue/laravel-follow包更新不适用现项目

### ISSUE THREAD

**Issue by leoxml** [summerblue/phphub5#87]
composer install 之后致命错误：

PHP Fatal error:  Trait 'Overtrue\LaravelFollow\FollowTrait' not found in /workspace/phphub5/app/Models/User.php on line 53

                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Trait 'Overtrue\LaravelFollow\FollowTrait' not found     

原来laravel-follow 已经更新，目录里没有Overtrue\LaravelFollow\FollowTrait，不适用项目，希望尽快修复。

**Comment by HakureiMarisa** [comment]
好像又崩了
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/laravel v5.4.9 requires laravel/framework 5.4.* -> satisfiable by laravel/framework[5.4.x-dev, v5.4.0, v5.4.1, v5.4.10, v5.4.11, v5.4.12, v5.4.13, v5.4.14, v5.4.15, v5.4.16, v5.4.17, v5.4.18, v5.4.19, v5.4.2, v5.4.20, v5.4.21, v5.4.22, v5.4.23, v5.4.24, v5.4.25, v5.4.26, v5.4.27, v5.4.28, v5.4.29, v5.4.3, v5.4.30, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8, v5.4.9] but these conflict with your requirements or minimum-stability.
...
   - Installation request for laravel/laravel dev-master -> satisfiable by laravel/laravel[dev-master].
    - overtrue/laravel-follow 1.0 requires laravel/laravel ^5.1 -> satisfiable by laravel/laravel[v5.1.0, v5.1.1, v5.1.11, v5.1.3, v5.1.33, v5.1.4, v5.2.0, v5.2.15, v5.2.23, v5.2.24, v5.2.27, v5.2.29, v5.2.31, v5.3.0, v5.3.10, v5.3.16, v5.3.30, v5.4.0, v5.4.15, v5.4.16, v5.4.19, v5.4.21, v5.4.23, v5.4.3, v5.4.30, v5.4.9].
    - Can only install one of: laravel/laravel[v5.1.0, dev-master].
    - Can only install one of: laravel/laravel[v5.1.1, dev-master].
    - Can only install one of: laravel/laravel[v5.1.11, dev-master].
    - Can only install one of: laravel/laravel[v5.1.3, dev-master].
    - Can only install one of: laravel/laravel[v5.1.33, dev-master].
    - Can only install one of: laravel/laravel[v5.1.4, dev-master].
    - Installation request for overtrue/laravel-follow 1.0 -> satisfiable by overtrue/laravel-follow[1.0].
