### ISSUE TITLE
项目 Clone 下来后，composer install 报错

### ISSUE THREAD

**Issue by lijinma** [summerblue/phphub5#9]
> Resolving dependencies through SAT
> Dependency resolution completed in 0.009 seconds
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for socialiteproviders/weixin v2.1.1 -> satisfiable by socialiteproviders/weixin[v2.1.1].
>     - socialiteproviders/weixin v2.1.1 requires socialiteproviders/manager ~2.1 -> no matching package found.

根据我的判断，应该是 composer.lock 中没有对应的 socialiteproviders/weixin v2.1.1，但是当时是如何安装的？奇怪啊。

我先使用 `composer update` 跑起来项目。

**Comment by summerblue** [comment]
@zhengjinghua Monkey 君

**Comment by summerblue** [comment]
此问题已修复，socialiteproviders 有很恶心的依赖关系。
