### ISSUE TITLE
你是这么狭隘的么

### ISSUE THREAD

**Issue by fifsky** [summerblue/phphub5#91]
我呼吁大家不要争吵，在使用composer的时候，可以给作者捐助，让作者有坚持下去的动力，这是你封号的理由么，本来我也从来没有登录过，封不封无所谓，我是不敢苟同你的做事风格

另，我所说的composer不仅仅是指composer中国，是泛指所有composer免费镜像的作者，你太狭隘了

**Comment by fifsky** [comment]
顺便给你提交个BUG，被禁用的账号，连退出登录的权限都没有了

**Comment by summerblue** [comment]
社区有规定，请保持友善，你语出不善，请看这里：

https://laravel-china.org/topics/4484/composer-mirror-use-help#reply24930

![image](https://cloud.githubusercontent.com/assets/324764/26199455/a0dfde70-3bfc-11e7-9a2c-831835fe6528.png)

**Comment by fifsky** [comment]
是么，我不知道那一句不善了，我是看了你评论里面那个  composer中国药丸的帖子的评论，感觉非常气愤，替作者不平才多说了几句，没有一句骂人的话，而那篇帖子里面多少人的评论比我说的恶心多了，我捐助多很多开源软件，以及文章作者，我只是看不惯很多人坐享其成，还埋怨抱怨

**Comment by summerblue** [comment]
把你的言行贴出来：

![image](https://cloud.githubusercontent.com/assets/324764/26199548/0ab8cb0e-3bfd-11e7-85f0-fc409b84e3d3.png)

你自己说 `很多人` `坐享其成`，虽然讲的好像正义凛然的样子，但是却透露着对我们做这个事情的指责。

出于对高可用性的追求，我们也提供了备份和选择的镜像，你爱用不用，我们也没赚你一分钱，你还出言不逊，你让在做免费维护的禅师大哥心里得多难受？

不屏蔽你屏蔽谁？

**Comment by fifsky** [comment]
谢谢你贴出来，公道自在人心，上面我已经说过了，我所说的composer不仅仅指我一直用的composer中国，对laravel-china的镜像我也是非常尊重的，我所说的很多人难道不是么，难道那些评论抱怨的人不是恶心么，我指责很多人坐享其成难道不对么，这和正义有毛线关系

**Comment by summerblue** [comment]
@fifsky 你捐助那是你的事情，赠人玫瑰手留余香，自己知道就行，就因为你捐赠了就喊别人 `坐享其成`？ 我还捐赠了一年小一千块的服务器费用呢。

另外，`药丸` 什么的，是社区的同学帖子里写的，我只是引用，来说明我们为何做这个事情。

互联网是个开放的地方，文字里透露不出来感情，别的社区我管不了，LC 我不会不管。
