### ISSUE TITLE
无法初始化数据表

### ISSUE THREAD

**Issue by mouyong** [summerblue/phphub5#93]
执行 `php artisan est:install` or `php artisan migrate` 都会报这个错误。

> PDO::__construct(): php_network_getaddresses: getaddrinfo failed:

![image](https://cloud.githubusercontent.com/assets/10336437/26769472/ce4bf680-49e1-11e7-882b-c7c14d775280.png)

**Comment by overtrue** [comment]
你的数据库用的是域名连接吧？DNS 解析失败

**Comment by mouyong** [comment]
@overtrue 在 laradock 中，.env使用的是 mysql

![image](https://cloud.githubusercontent.com/assets/10336437/26773311/5cfe565a-49fd-11e7-9c53-3b85d11daf81.png)

其他的项目都是这么配置的。
我试试到容器 workspace 中执行，看看能不能解析，因为这是在 windows 执行的，可能是这个原因导致的失败

**Comment by mouyong** [comment]
@overtrue 解决了，因为在 windows 中执行，解析的时候无法找到 mysql 对应的 容器，进入 workspace 容器或其他拥有 php 环境的容器后，便可以执行了。已完成初始化，谢谢:)
