### ISSUE TITLE
页码显示错误的问题

### ISSUE THREAD

**Issue by jormin** [summerblue/phphub5#94]
地址栏访问的是`page=18`，但页面下方的页码却是`20`被激活，好像不管`page`是多少，下面显示`active`的都是`page+2`。

![image](https://user-images.githubusercontent.com/5519318/27529581-a2c67efc-5a87-11e7-968e-1c7bccd1ce98.png)

**Comment by summerblue** [comment]
这是自动加载造成的，现在是自动最多加载三页。
