### ISSUE TITLE
phphub下的sendcloud发邮件需如何配置

### ISSUE THREAD

**Issue by Thanosss** [summerblue/phphub5#96]
在.env内已经配置了sendcloud账号与秘钥，还是无法发送邮件，请问这个还需要再哪里配置吗?还有邮件发送的日志是在哪里能查看呢？

**Comment by overtrue** [comment]
所以你的意思是让我们从无限种可能中猜测 “无法发送邮件” 的原因？

**Comment by summerblue** [comment]
还需要在 sendcloud 后台建立邮件模板。

**Comment by Thanosss** [comment]
您好，这边已经建立好sendcloud的模板了，邮件也是无法发送。
env配置文件里加入了sendcloud
![env sendcloud](https://user-images.githubusercontent.com/20548539/28414934-39779b3c-6d80-11e7-9cd3-92e1c91577dc.jpg)
这是phphub原始的发件模块未作任何修改
![phphub](https://user-images.githubusercontent.com/20548539/28414960-51bc1524-6d80-11e7-99b3-fc864c8456fd.jpg)
已经在sendcloud内建立好邮件模板
![sendcloud](https://user-images.githubusercontent.com/20548539/28414988-67aa850a-6d80-11e7-9ce0-cb3b7abd7549.jpg)
测试邮件显示已发送，但实际邮件未能成功发送。
![default](https://user-images.githubusercontent.com/20548539/28415009-7fb48268-6d80-11e7-816d-dc7b3c1c2c36.jpg)
我改动过的地方有.env内加入sendcloud，在sendcloud里建立了邮件模板。
请问这是我配置上存在问题还是我有地方遗漏的。
还得劳烦各位！谢谢！
